### ISSUE TITLE
this.constructor.name is mangled during minification

### ISSUE THREAD

**Issue by meonkeys** [arsnebula/classx#1]
[Here's a tiny Meteor app that demonstrates the bug](https://github.com/meonkeys/classx-2-0-3-minification-bug).

To repro, run app with `meteor run --production`, hit with a web browser and look at the browser's developer console.

Expected:

    name in constructor is MyClass
    name just past constructor is MyClass

Actual:

    name in constructor is o
    name just past constructor is o

I'm not sure if minification is deterministic. Your actual browser console output may vary.

The "Expected" output is seen during `meteor run` (development mode).

Related:

* <http://stackoverflow.com/questions/332422/how-do-i-get-the-name-of-an-objects-type-in-javascript#comment19454004_332429>
* <https://github.com/jashkenas/coffeescript/issues/2052>
* <http://code.dblock.org/2012/10/13/how-do-i-get-the-name-of-an-objects-type-in-javascript.html>

**Comment by chrismbeckett** [comment]
Hey Adam, thanks for the report. Pretty common that constructor names get managed by minification. If I was doing the minification myself I might be able to choose the minification engine or set options, etc., but this is magically done automatically by MeteorJS.

Is there a *application* reason you need the names intact? I tend to rely on *instanceof* if I want to check on the type of class to avoid any functional dependency on the constructor names (which are optional anyway).

**Comment by meonkeys** [comment]
> Pretty common that constructor names get managed by minification.

Ah, thank you. That's helpful, and it confirms my suspicions after doing some research.

> Is there a application reason you need the names intact?

Yes, I was using constructor names, and didn't notice problems until I minified. :) I guess I'll just set the name of the class on a property.

Thanks, Chris!
